# Site settings
title: Philms Blog
SEOTitle: Philms Blog
header-img: img/Main-bg.jpg
email: philms|outlook|com
description: "一个懒人。"
keyword: "Philms, GTD, 摄影, 笔记, 信息"
url: "https://philms.date"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/philms0/philms0.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一把刀的锋刃很不容易越过；因此智者说得救之道是困难的。"
sidebar-avatar: /img/philms.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
#weibo_username:     philms
zhihu_username:     philms
github_username:    philms0
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   philms




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: philms

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 4646a26e349d47cb3354                            #生成的clientID 参考自https://segmentfault.com/a/1190000016060379
  clientSecret: b2b444a510d0d30222f17903ecd30bdc84e2062f    #生成的clientSecret 从这里申请https://github.com/settings/applications/new
  repo: philms0.github.io    #仓库名称
  owner: philms    #github用户名
  admin: philms
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: philms.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
    #{
       # title: "WY",
       # href: "http://zhengwuyang.com"
  #  },{
        #title: "简书·BY",
      #  href: "http://www.jianshu.com/u/e71990ada2fd"
   # },{
   #     title: "Apple",
     #   href: "https://apple.com"
  #  },{
   #     title: "Apple Developer",
    #    href: "https://developer.apple.com/"
  #  }
#]
